version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Start DynamoDB
          command: |
            sudo apt update && sudo apt install -y default-jre default-jdk
            curl -k -L -o dynamodb-local.tgz https://s3.ap-south-1.amazonaws.com/dynamodb-local-mumbai/dynamodb_local_latest.tar.gz
            tar -xzf dynamodb-local.tgz
            java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb
          background: true
      - run: sleep 60
      - run: make install-proto
      - run: make build
      - run:
          name: Run tests
          no_output_timeout: 2m
          command: |
            mkdir -p ~/.aws
            echo "[default]\naws_access_key_id = sometoken\naws_secret_access_key = sometoken\nregion = us-east-2" > ~/.aws/credentials
            export AWS_REGION="us-east-2"
            export DISABLE_SSL="true"
            export DB_ENDPOINT="localhost:8000"
            make tests
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts