version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: make install-proto
      - run: make build
      - run:
          command: |
            make tests
            mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts